# Kubernetes Job Template for Kaniko Builds using Generated Dockerfiles
#
# This template is used when the Dockerfile is generated by the LLM and stored
# in a ConfigMap rather than being present in the repository.
#
# Template Variables:
#   namespace              - Kubernetes namespace for the job
#   jobName                - Unique job name (should include timestamp or commit SHA)
#   repoUrl                - GitHub repository URL (e.g., github.com/owner/repo)
#   branch                 - Git branch to build from
#   commitSha              - Specific commit SHA to build
#   imageDest              - Full destination image path (e.g., harbor.example.com/project/image:tag)
#   gitSecretName          - Name of Kubernetes secret containing git credentials
#   registrySecretName     - Name of Kubernetes secret containing registry credentials
#   dockerfileConfigMap    - Name of ConfigMap containing the generated Dockerfile
#
# Secrets Required:
#   Git Secret (gitSecretName):
#     - GIT_USERNAME: GitHub username or token name
#     - GIT_PASSWORD: GitHub personal access token
#
#   Registry Secret (registrySecretName):
#     - config.json: Docker registry config for Harbor authentication
#
# ConfigMap Required:
#   Dockerfile ConfigMap (dockerfileConfigMap):
#     - Dockerfile: The generated Dockerfile content
#     - .dockerignore: (optional) The generated .dockerignore content

apiVersion: batch/v1
kind: Job
metadata:
  name: {{jobName}}
  namespace: {{namespace}}
  labels:
    app: kaniko-build
    managed-by: dangus-cloud
    commit-sha: {{commitSha}}
    dockerfile-source: generated
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 2
  activeDeadlineSeconds: 1800
  template:
    metadata:
      labels:
        app: kaniko-build
        job-name: {{jobName}}
    spec:
      restartPolicy: Never
      initContainers:
        # Clone the repository to get source code
        - name: git-clone
          image: alpine/git:latest
          env:
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{gitSecretName}}
                  key: GIT_USERNAME
            - name: GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{gitSecretName}}
                  key: GIT_PASSWORD
          command:
            - /bin/sh
            - -c
            - |
              git clone --single-branch --branch {{branch}} \
                https://${GIT_USERNAME}:${GIT_PASSWORD}@{{repoUrl}} /workspace && \
              cd /workspace && \
              git checkout {{commitSha}}
          volumeMounts:
            - name: workspace
              mountPath: /workspace
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        # Copy the generated Dockerfile into the workspace
        - name: copy-dockerfile
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              cp /generated/Dockerfile /workspace/Dockerfile
              if [ -f /generated/.dockerignore ]; then
                cp /generated/.dockerignore /workspace/.dockerignore
              fi
              echo "=== Generated Dockerfile ==="
              cat /workspace/Dockerfile
              echo "=== End Dockerfile ==="
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: generated-dockerfile
              mountPath: /generated
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--dockerfile=/workspace/Dockerfile"
            - "--context=dir:///workspace"
            - "--destination={{imageDest}}"
            - "--cache=true"
            - "--cache-ttl=24h"
            - "--snapshot-mode=redo"
            - "--log-format=text"
            - "--skip-tls-verify"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: docker-config
              mountPath: /kaniko/.docker
              readOnly: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
      volumes:
        - name: workspace
          emptyDir: {}
        - name: docker-config
          secret:
            secretName: {{registrySecretName}}
            items:
              - key: config.json
                path: config.json
        - name: generated-dockerfile
          configMap:
            name: {{dockerfileConfigMap}}
